CMSPersonal/Models/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CMSPersonal.Models
{
    public partial class Blog
    {
        public int Id { get; set; }

        [Required]
        public int CategoryId { get; set; }
        public int? PrimaryImageId { get; set; }

        public string PrimaryImageUrl { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Url { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }

        [Required]
        public string Description { get; set; }
        public DateTime AddedOn { get; set; }

        [Required]
        public bool Status { get; set; }
    }
}

CMSPersonal/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CMSPersonal.Infraestructure;
using CMSPersonal.Models;
using CMSPersonal.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Drawing;
using System.Drawing.Drawing2D;

namespace CMSPersonal.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MediaController : Controller
    {
        private IHostingEnvironment hostingEnvironment;
        public MediaController(IHostingEnvironment environment)
        {
            hostingEnvironment = environment;
        }
        public ActionResult Index()
        {
            Media media = new Media();
            media.MediaDate = GetMediaDate();
            media.Result = GetMediaWithPaging("all", "all", 1, null);
            return View(media);
        }

        [HttpPost]
        public ActionResult Index(Models.Media mMedia, string date)
        {
            mMedia.MediaDate = GetMediaDate();
            return View(mMedia);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(IFormFile[] mediaUpload)
        {
            List<FileUpload> lFileUpload = new List<FileUpload>();

            if (mediaUpload[0] == null)
                ViewBag.Result = "No Files Selected";
            else
            {
                foreach (IFormFile file in mediaUpload)
                {
                    FileUpload fileUpload = new FileUpload();
                    /*Start inserting of the files*/
                    string[] resultInsert = InsertMedia(file, null, null);
                    string resultUpload = "";
                    if (resultInsert[0] == "Success")
                        resultUpload = await UploadMedia(file, resultInsert[1]);
                    /*End*/

                    fileUpload.name = file.FileName;
                    fileUpload.id = Convert.ToInt32(resultInsert[2]);

                    string savedPath150x150 = "";
                    bool isImage = IsImage(file.FileName);
                    if (isImage)
                    {
                        savedPath150x150 = "~/" + GetPath() + resultInsert[1];// remove this line when doing cropping

                        //Start the Cropping of Image
                        Dictionary<string, bool> dictionary = CheckFileCropApplicable(file);
                        string originalFileName = resultInsert[1];
                        string newFileName150x150 = originalFileName.Substring(0, originalFileName.LastIndexOf('.')) + "150X150" + originalFileName.Substring(originalFileName.LastIndexOf('.'), originalFileName.Length - originalFileName.LastIndexOf('.'));
                        string newFileName250x250 = originalFileName.Substring(0, originalFileName.LastIndexOf('.')) + "250X250" + originalFileName.Substring(originalFileName.LastIndexOf('.'), originalFileName.Length - originalFileName.LastIndexOf('.'));
                        string newFileName500x500 = originalFileName.Substring(0, originalFileName.LastIndexOf('.')) + "500X500" + originalFileName.Substring(originalFileName.LastIndexOf('.'), originalFileName.Length - originalFileName.LastIndexOf('.'));

                        foreach (var item in dictionary)
                        {
                            if ((item.Key == "Crop150") && (item.Value == true))
                            {
                                resultInsert = InsertMedia(file, newFileName150x150, fileUpload.id);
                                savedPath150x150 = CropImage(GetPath(), originalFileName, resultInsert[1], 150, 150, true);
                            }
                            else if ((item.Key == "Crop250") && (item.Value == true))
                            {
                                resultInsert = InsertMedia(file, newFileName250x250, fileUpload.id);
                                CropImage(GetPath(), originalFileName, resultInsert[1], 250, 250, true);
                            }
                            else if ((item.Key == "Crop500") && (item.Value == true))
                            {
                                resultInsert = InsertMedia(file, newFileName500x500, fileUpload.id);
                                CropImage(GetPath(), originalFileName, resultInsert[1], 500, 500, true);
                            }
                        }
                        //End
                    }
                    fileUpload.url = savedPath150x150 == "" ? "~/images/file-icon.png" : savedPath150x150;
                    lFileUpload.Add(fileUpload);
                }
            }
            if (lFileUpload.Count > 0)
                ViewBag.Result = lFileUpload.Count + " Files Uploaded";
            return View(lFileUpload);
        }

        public ActionResult Update(int id)
        {
            Media media = new Media();
            media = GetMediaById(id);
            ViewBag.Title = "Update Page";
            return View(media);
        }

        [HttpPost]
        public ActionResult Update(Media media)
        {
            if (IsImage(media.Name))
                media.DisplayUrl = media.Url;
            else
                media.DisplayUrl = "images/file-icon.png";

            if (ModelState.IsValid)
            {
                var param = new SqlParameter[] {
                                    new SqlParameter() {
                                        ParameterName = "@Id",
                                        SqlDbType =  System.Data.SqlDbType.Int,
                                        Direction = System.Data.ParameterDirection.Input,
                                        Value = media.Id
                                    },
                                    new SqlParameter() {
                                        ParameterName = "@Name",
                                        SqlDbType =  System.Data.SqlDbType.VarChar,
                                        Direction = System.Data.ParameterDirection.Input,
                                        Size = 100,
                                        Value = media.Name
                                    },
                                    new SqlParameter() {
                                        ParameterName = "@Url",
                                        SqlDbType =  System.Data.SqlDbType.VarChar,
                                        Direction = System.Data.ParameterDirection.Input,
                                        Size = 250,
                                        Value = media.Url
                                    },
                                    new SqlParameter() {
                                        ParameterName = "@Title",
                                        SqlDbType =  System.Data.SqlDbType.VarChar,
                                        Direction = System.Data.ParameterDirection.Input,
                                        Size = 100,
                                        Value = media.Title
                                    },
                                    new SqlParameter() {
                                        ParameterName = "@Alt",
                                        SqlDbType =  System.Data.SqlDbType.VarChar,
                                        Direction = System.Data.ParameterDirection.Input,
                                        Size = 100,
                                        Value = media.Alt
                                    },
                                    new SqlParameter() {
                                        ParameterName = "@Description",
                                        SqlDbType =  System.Data.SqlDbType.VarChar,
                                        Direction = System.Data.ParameterDirection.Input,
                                        Size = 100,
                                        Value = media.Description
                                    },
                                    new SqlParameter()
                                    {
                                        ParameterName = "@Result",
                                        SqlDbType = System.Data.SqlDbType.VarChar,
                                        Direction = System.Data.ParameterDirection.Output,
                                        Size = 50
                                    }};
                using (var context = new CMSContext())
                {
                    context.Database.ExecuteSqlCommand("[dbo].[sp_UpdateMedia] @Id, @Name, @Url, @Title, @Alt, @Description, @Result out", param);
                }
                ViewBag.Title = "Update Media";
                ViewBag.result = Convert.ToString(param[6].Value);
            }
            return View(media);
        }

        public string DeleteMedia(string ids, string paths)
        {
            using (var context = new CMSContext())
            {
                var param = new SqlParameter[] {
                                    new SqlParameter() {
                                        ParameterName = "@Id",
                                        SqlDbType =  System.Data.SqlDbType.VarChar,
                                        Size=50,
                                        Direction = System.Data.ParameterDirection.Input,
                                        Value = ids
                                    }};
                context.Database.ExecuteSqlCommand("[dbo].[sp_DeleteMedia] @Id", param);
            }
            foreach (string path in paths.Split(','))
            { 

CMSPersonal/Views/Blog/Add.cshtml
@model Blog
<script src="~/js/CKEditor/ckeditor.js" type="text/javascript" language="javascript"></script>

<article>
    <h1>@ViewBag.Title</h1>
    <h2>@TempData["result"]</h2>

    <form method="post">
        <div class="control">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="text-box" />
            <span asp-validation-for="Name"></span>
        </div>
        <div class="lineControl">
            <label asp-for="Url"></label>:-<label>@Context.Request.Scheme://@Context.Request.Host/</label>
            <input asp-for="Url" class="text-box" />-id-@Model.Id
            <span asp-validation-for="Url"></span>
        </div>
        <div class="control">
            <label asp-for="PrimaryImageId"></label>
            <div class="primaryImage">
                <img id="primaryImg" src="@Model.PrimaryImageUrl" />
                <img id="crossImg" src="~/images/close.png" />
                <input type="hidden" asp-for="PrimaryImageId" />
                <input type="hidden" asp-for="PrimaryImageUrl" />
            </div>
        </div>
        <div class="control">
            <label asp-for="CategoryId"></label>
            <select class="form-control" asp-for="CategoryId" asp-items="ViewBag.CategoryList">
                <option selected value="Select">Select</option>
            </select>
            <span asp-validation-for="CategoryId"></span>
        </div>
        <div class="control">
            <label asp-for="Description"></label>
            <textarea asp-for="Description"></textarea>
            <script type="text/javascript" language="javascript">
                CKEDITOR.replace(@Html.IdFor(model => model.Description));
                CKEDITOR.config.allowedContent = true
                CKEDITOR.ignoreEmptyParagraph = true;
            </script>
            <span asp-validation-for="Description"></span>
        </div>
        <div class="control">
            <label asp-for="MetaTitle"></label>
            <input asp-for="MetaTitle" class="text-box" />
            <span asp-validation-for="MetaTitle"></span>
        </div>
        <div class="control">
            <label asp-for="MetaKeyword"></label>
            <input asp-for="MetaKeyword" class="text-box" />
            <span asp-validation-for="MetaKeyword"></span>
        </div>
        <div class="control">
            <label asp-for="MetaDescription"></label>
            <input asp-for="MetaDescription" class="text-box" />
            <span asp-validation-for="MetaDescription"></span>
        </div>
        <div class="control">
            <label asp-for="Status"></label>
            <select class="form-control" asp-for="Status">
                <option value="true">Active</option>
                <option value="false">InActive</option>
            </select>
        </div>
        <div class="control">
            <button type="submit">Submit</button>
        </div>
    </form>

    <!-- Bootstrap Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <div class="mediaToolbar">
                        <div class="bulkDiv">
                            <div class="first">
                                <a asp-controller="Media" asp-action="Add" target="_blank" class="h1NewPage">Add New</a>
                                <select id="date" asp-items="ViewBag.MediaDate">
                                    <option value="All">Date</option>
                                </select>
                            </div>
                        </div>
                        <div class="search">
                            <input id="serchName" type="text" placeholder="Search" />
                        </div>
                    </div>
                </div>
                <div class="modal-body" style="overflow:auto;height:300px;">
                    <ul id="allMedia"></ul>

                    <input type="hidden" id="page" value="1" />
                    <img id="loadingImg" src="~/images/loading.gif" hidden="hidden" class="right" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Set as Primary Image</button>
                </div>
            </div>
            <!-- END Modal content-->

        </div>
    </div>
    <!-- END Bootstrap Modal -->
</article>

@section Script {
    <script>
        $(document).ready(function () {
            ShowHideCross();

            $("#primaryImg").click(function () {
                $("#myModal").modal("show");
                if ($('#page').val() != 'end') {
                    Initialize();
                    GetMediaWithPaging()
                }
            });

            $("#crossImg").click(function () {
                $("#primaryImg").attr("src", "/images/addphoto.jpg")
                $("#PrimaryImageId").val("");
                $("#PrimaryImageUrl").val("");

                $(this).hide();
            });

            function ShowHideCross() {
                if ($("#primaryImg").attr("src") != "/images/addphoto.jpg")
                    $("#crossImg").css("display", "block")
                else
                    $("#crossImg").css("display", "none")
            }

            $(".modal-footer > button").click(function () {
                var imageId = $("#allMedia li input[type='checkbox']:checked").siblings().attr("href").replace("/Media/Update/", "")
                var imageUrl = $("#allMedia li input[type='checkbox']:checked").parent().find("img").attr("data-url")

                $("#primaryImg").attr("src", imageUrl)
                $("#PrimaryImageUrl").val(imageUrl);
                $("#PrimaryImageId").val(imageId);

                ShowHideCross();
            });

            $("#allMedia").on("change", "input[type='checkbox']", function () {
                if ($(this).prop('checked')) {
                    $("#allMedia li input[type='checkbox']").prop("checked", false);
                    $("#allMedia li").removeClass("selected");
                    $(this).prop("checked", true);
                    $(this).parent().addClass("selected");
                }
                else
                    $(this).parent().removeClass("selected");
            });

            $('.modal-body').scroll(function () {
                var div = $(this);
                if (div[0].scrollHeight - div.scrollTop() - 100 <= div.height()) {
                    //alert('Reached the bottom!');
                    if ($('#page').val() != 'end') {
                        var page = parseInt($('#page').val());
                        page = page + 1;
                        $('#page').val(page);
                        GetMediaWithPaging();
                    }
                }
            });

            $("#serchName").keyup(function () {
                Initialize();
                GetMediaWithPaging();
            });

            $('#date').change(function () {
                Initialize();
                GetMediaWithPaging();
            });

            function GetMediaWithPaging() {
                var date = $("#date").val();
                var page = $('#page').val();
                var name = $('#serchName').val();

                //http://stackoverflow.com/questions/1191485/how-to-call-ajaxstart-on-specific-ajax-calls
                $(document).unbind(".firstCall");
                $(document).on("ajaxStart.firstCall", function () {
                    $("#loadingImg").show();
                });
                $(document).on("ajaxStop.firstCall", function () {
                    $("#loadingImg").hide();
                });

                $.ajax({
                    type: "POST",
                    url: "/Blog/GetMediaWithPaging",
                    data: {date: date, page: page, name: name},
                    dataType: "html",
                    success: function (msg) {
                        if (msg == '')
                            $('#page').val('end');
                        else
                            $("#allMedia").append(msg);
                    },
                    error: function (req, status, error) {
                        alert(error);
                    }
                });
                return false;
            }

            function Initialize() {
                $('#page').val('1');
                $('#allMedia').html('');
            }
        });
    </script>
}

CMSPersonal/Views/Blog/Index.cshtml
@model BlogList
@{
    ViewBag.Title = "All Blog";
}
<article>
    <h1>All Blog <a class="h1NewPage" asp-action="Add">Add Blog</a></h1>
    <h2 id="messageH2"></h2>
    <div id="infoDiv">
        <div class="pageTypeDiv">
            <ul>
                @{
                    string statusAllClass = null, statusActiveClass = null, statusInActiveClass = null;
                    if (Model.status == null)
                    {
                        statusAllClass = "fontWeightBold";
                    }
                    else if (Model.status == 1)
                    {
                        statusActiveClass = "fontWeightBold";
                    }
                    else if (Model.status == 0)
                    {
                        statusInActiveClass = "fontWeightBold";
                    }
                }
                <li><a asp-action="Index" class="@statusAllClass">All<span>(@Model.allTotal)</span></a></li>
                <li><a asp-action="Index" asp-route-status="1" class="@statusActiveClass">Active<span>(@Model.activeTotal)</span></a></li>
                <li><a asp-action="Index" asp-route-status="0" class="@statusInActiveClass">Inactive<span>(@Model.inactiveTotal)</span></a></li>
            </ul>
        </div>
        <div class="pageSearchDiv">
            <form asp-action="Index" method="get">
                <input type="text" asp-for="searchText" /> <button type="submit">Search</button>
            </form>
        </div>
    </div>
    <div id="workDiv">
        <div class="bulkDiv">
            <select asp-for="status">
                <option value="Status">Status</option>
                <option value="1">Active</option>
                <option value="0">InActive</option>
            </select>
            <button type="submit" id="bulkSubmit">Apply</button>
        </div>
        <div class="pagingDiv">
            <div page-model="@Model.pagingInfo" status="@Model.status" search-text="@Model.searchText" page-action="Index" page-classes-enabled="true" page-class="paging" page-class-selected="active"></div>
        </div>
        <div id="pageDiv">
            <table>
                <thead>
                    <tr class="row"><th class="col-sm-1"><input id="mainCheckBox" type="checkbox" /></th><th class="col-sm-5">Name</th><th class="col-sm-3">Status</th><th class="col-sm-3">Added On</th></tr>
                </thead>
                <tbody id="pageTbody">
                    @foreach (var p in Model.blog)
                    {
                        @Html.Partial("Blog", p);
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4">
                            <div class="pagingDiv">
                                <div page-model="@Model.pagingInfo" status="@Model.status" search-text="@Model.searchText" page-action="Index" page-classes-enabled="true" page-class="paging" page-class-selected="active"></div>
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</article>
@section Script {
    <script type="text/javascript">
        $(document).ready(function () {
            $("#pageDiv").find('input[type="checkbox"]').each(function () {
                $(this).prop("checked", false);
            });
            $("#bulkSubmit").click(function (e) {
                var idChecked = GetIdChecked();
                var statusToChange = $("#status").val();
                $.ajax({
                    type: "POST",
                    url: "/Blog/UpdateBulkStatus",
                    data: {idChecked: idChecked, statusToChange: statusToChange},
                    dataType: "html",
                    success: function (msg) {
                        $("#messageH2").html(msg);
                        setTimeout(function () { location.reload(); }, 2000);
                    },
                    error: function (req, status, error) {
                        alert(error);
                    }
                });
                return false;
            });
            function GetIdChecked() {
                var idChecked = "";
                $("#pageTbody").find('input[type="checkbox"]').each(function () {
                    if ($(this).prop("checked")) {
                        idChecked = idChecked + this.id + ",";
                    }
                });
                return idChecked.substring(0, idChecked.length - 1);
            }
            $("#mainCheckBox").click(function () {
                if ($(this).is(":checked")) {
                    $("#pageTbody").find('input[type="checkbox"]').each(function () {
                        $(this).prop("checked", true);
                    });
                }
                else {
                    $("#pageTbody").find('input[type="checkbox"]').each(function () {
                        $(this).prop("checked", false);
                    });
                }
            });
        });
    </script>
}